### ISSUE TITLE
Example Command for Replicating Experiment Fails Due to Assertion Error

### ISSUE THREAD

**Issue by runchu-tian** [Real-Doris-Mae/Doris-Mae-Dataset#1]
### GitHub Issue: Example Command for Replicating Experiment Fails Due to Assertion Error

**Title**: Example Command for Replicating Experiment Fails Due to Assertion Error

**Description**:  
The provided example command to replicate the experiment in the documentation is failing during execution due to an `AssertionError`. The dataset appears to load correctly, and initial processing completes without issues, but an error occurs when calculating the random baseline for ranking results.

Here is the command used:
```bash
python3 evaluation.py -o "query" -c "0,1,2" -b 200 -bt True
```

**Output**:
```bash
loading dataset.... may take a while
raw dataset size 100
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 96.94it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 97.15it/s]

Cuda : 0,1,2
Level : query
User defined batch size : 200
...

ranking results for ernie are already calculated
Traceback (most recent call last):                                                                                                                                                                                        
  File "evaluation.py", line 79, in <module>
    random_result_dict = get_random_baseline(gpt_result, rank, test_suites, trials = 100)
  File "/home/USER/proj/Doris-Mae-Dataset/benchmarking/rank_performance_util.py", line 196, in get_random_baseline
    value = get_metric(gpt_result, curr_random_rank, test_name, k)
  File "/home/USER/proj/Doris-Mae-Dataset/benchmarking/rank_performance_util.py", line 241, in get_metric
    assert len(gpt_result) == len(method_rank), f"{len(gpt_result)}; {len(method_rank)}"
AssertionError: 100; 50
```

**Issue**:  
The error occurs in the function `get_metric`, specifically an assertion that fails due to a mismatch in lengths between `gpt_result` and `method_rank`. The command reports:
```bash
AssertionError: 100; 50
```
It seems that `gpt_result` contains 100 elements, while `method_rank` only has 50. This mismatch causes the experiment to fail.

**Steps to Reproduce**:
1. Run the command provided in the documentation to replicate the experiment:
   ```bash
   python3 evaluation.py -o "query" -c "0,1,2" -b 200 -bt True
   ```
2. Observe the error during the ranking phase when calling `get_random_baseline`.

**Expected Behavior**:  
The experiment should complete without assertion errors and provide results for the models specified.

**Possible Cause**:  
The length of `gpt_result` does not match the expected length of `method_rank`, which might indicate a mismatch in the dataset or processing steps. This could be related to incomplete or incorrect rankings being generated.
  
**Suggestions**:
- Please verify the ranking logic or dataset size assumptions in the `get_metric` function.
- Consider adding additional logging to provide insights into why the length of `method_rank` is shorter than expected.

Let me know if you need any more details!

**Comment by runchu-tian** [comment]
This issue can be solved by removing all the cached output from `benchmarking/dataset/rankings/query`.
- It seems that the initial cached results are problematic. 
- Just remove them for regeneration, and you will get the correct data
