### ISSUE TITLE
[Error] Assertion error when launching with the provided command

### ISSUE THREAD

**Issue by MHoubre** [Real-Doris-Mae/Doris-Mae-Dataset#2]
Hello,
I followed the instructions for the installation of Doris-Mae and when I am using the provided command to reproduce the results, in throws an "Assertion Error".

To reproduce, I launched the command with only two gpus and a batch size of 20: Here is the modified command
```
python3 evaluation.py -o "query" -c "0,1" -b 20 -bt True
```

This was a test run without any modification on the dataset. I am just trying to run the code.

Here is the error message:

``` 
raw dataset size 100
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 85.95it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 86.43it/s]
Cuda : 0,1
Level : query
User defined batch size : 20
======================================== Models Specifications ========================================
===============================================================================================
Model name : e5 ; Query mode : paragraph ; Abstract mode : paragraph ; Metric : cosine ; Aggregation : mean_max
Model name : ts_aspire ; Query mode : paragraph ; Abstract mode : paragraph ; Metric : l2 ; Aggregation : mean_max
Model name : ot_aspire ; Query mode : paragraph ; Abstract mode : paragraph ; Metric : wasserstein ; Aggregation : mean_max
Model name : simcse ; Query mode : paragraph ; Abstract mode : paragraph ; Metric : cosine ; Aggregation : mean_max
Model name : specter ; Query mode : paragraph ; Abstract mode : paragraph ; Metric : l2 ; Aggregation : mean_max
Model name : specterv2 ; Query mode : paragraph ; Abstract mode : paragraph ; Metric : l2 ; Aggregation : mean_max
Model name : sentbert ; Query mode : sentence ; Abstract mode : sentence ; Metric : cosine ; Aggregation : mean_max
Model name : rocketqa ; Query mode : paragraph ; Abstract mode : paragraph ; Metric : cosine ; Aggregation : mean_max
Model name : ance ; Query mode : sentence ; Abstract mode : sentence ; Metric : cosine ; Aggregation : mean_max
Model name : simlm ; Query mode : paragraph ; Abstract mode : paragraph ; Metric : cosine ; Aggregation : mean_max
Model name : spladev2 ; Query mode : paragraph ; Abstract mode : paragraph ; Metric : cosine ; Aggregation : mean_max
Model name : colbertv2 ; Query mode : paragraph ; Abstract mode : paragraph ; Metric : cosine ; Aggregation : mean_max
Model name : scibert ; Query mode : paragraph ; Abstract mode : paragraph ; Metric : cosine ; Aggregation : mean_max
Model name : ernie ; Query mode : paragraph ; Abstract mode : paragraph ; Metric : cosine ; Aggregation : mean_max
Model name : bm25 ; Query mode : paragraph ; Abstract mode : paragraph ; Metric : cosine ; Aggregation : mean_max
Model name : tfidf ; Query mode : paragraph ; Abstract mode : paragraph ; Metric : cosine ; Aggregation : mean_max
===============================================================================================
===============================================================================================
ranking results for ernie are already calculated
Traceback (most recent call last):                                                                                                                                                                         
  File "evaluation.py", line 79, in <module>
    random_result_dict = get_random_baseline(gpt_result, rank, test_suites, trials = 100)
  File "/home/houbre/Documents/Dev/Doris-Mae-Dataset/benchmarking/rank_performance_util.py", line 196, in get_random_baseline
    value = get_metric(gpt_result, curr_random_rank, test_name, k)
  File "/home/houbre/Documents/Dev/Doris-Mae-Dataset/benchmarking/rank_performance_util.py", line 241, in get_metric
    assert len(gpt_result) == len(method_rank), f"{len(gpt_result)}; {len(method_rank)}"
AssertionError: 100; 50
```

**Comment by pintoliveira** [comment]
Hello, Were you able to solve this problem? I face the same issue.

**Comment by MHoubre** [comment]
Hello,
No sorry I have not been able to solve the problem.
However, I was able to obtain some results with the option "60_query" with the following line:

```
python evaluation.py -o "60_query" -c "0,1" -b 20 -bt True
```
Hope it helps.

**Comment by kwang927** [comment]
Hi @MHoubre ,

Thanks for reaching out and for trying out our work!

This assertion error was due to outdated cached ranking results located in `benchmarking/dataset/rankings/`. We had updated the dataset during the paper's review process, but overlooked removing these old cache files.

I've updated the repository to remove the old cached rankings. Please pull the latest changes, and the assertion error should be resolved.
